apiVersion: v1
kind: Service
metadata:
  name: hello-service-blue
spec:
  selector:
    app: hello
    release: stable
    tier: helloapp
    environement: production
    partition: training-k8s
    version : 1.0.0
  type: ClusterIP
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80

