apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      release: canary
      tier: helloapp
      environement: production
      partition: training-k8s
  template:
    metadata:
      labels:
        app: hello
        release: canary
        tier: helloapp
        environement: production
        partition: training-k8s
    spec:
      containers:
      - name: hello
        image: kelseyhightower/hello:2.0.0
        ports:
          - name: hello-port
            containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
