apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
    tier: helloapp
    environement: production
    partition: training-k8s
  type: ClusterIP
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80

