apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector: // Une des manières possibles. Exemple avec matchLabels et matchExpressions
    matchLabels:
      app: frontend
      environement: production
      release: stable
      version: 2.0.0 
    matchExpressions:  
      - {key: partition, operator: In, values: [training-k8s, training-treeptik-k8s, super-students]}
      - {key: tier, operator: NotIn, values: [authentification, webserver]} 
  template:
    metadata:
      labels:
        app: frontend
        environement: production  
        partition: training-k8s      
        release: stable
        tier: fronthttps
        version: 2.0.0
    spec:
      containers:
        - name: nginx
          image: "nginx:1.9.14"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "nginx-frontend-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "tls-certs"
              mountPath: "/etc/tls"
      volumes:
        - name: "tls-certs"
          secret:
            secretName: "tls-certs"
        - name: "nginx-frontend-conf"
          configMap:
            name: "nginx-frontend-conf"
            items:
              - key: "frontend.conf"
                path: "frontend.conf"