apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: auth
      environement: production
      partition: training-k8s
      release: stable
      tier: authentification
  template:
    metadata:
      labels:
        app: auth
        environement: production
        partition: training-k8s
        release: stable
        tier: authentification
    spec:
      containers:
      - name: auth
        image: kelseyhightower/auth:2.0.0
        ports:
          - name: auth-port
            containerPort: 80
        resources:
          limits:
            cpu: 50m # 0.2 works too
            memory: 20Mi
