apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      release: stable
      tier: fronthttps
      environement: production
      partition: training-k8s
      version: 1.0.0  
  template:
    metadata:
      labels:
        app: frontend
        release: stable
        tier: fronthttps
        environement: production
        partition: training-k8s
        version: 1.0.0  
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.14
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi

