apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      realease: stable
      tier: fronthttps
      environement: dev
      partition: training-k8s
  template:
    metadata:
      labels:
        name: frontend
        labels:
          app: frontend
          realease: stable
          tier: fronthttps
          environement: dev
          partition: training-k8s
    spec:
      containers:
        - name: nginx
          image: nginx:1.9.14
          ports:
            - name: auth-port
              containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: 50Mi

