apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      realease: stable
      tier: fronthttps
      environement: production
      partition: training-k8s 
  template:
    metadata:
      labels:
        app: frontend
        realease: stable
        tier: fronthttps
        environement: production
        partition: training-k8s
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.14
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi

