apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendv2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      realease: stable
      tier: fronthttps
      environement: production
      partition: training-k8s
      version: 2.0.0  
  template:
    metadata:
      labels:
        app: frontend
        realease: stable
        tier: fronthttps
        environement: production
        partition: training-k8s
        version: 2.0.0  
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.14
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: 50Mi

