apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
      realease: stable
      tier: helloapp
      environement: production
      partition: training-k8s
  template:
    metadata:
      labels:
        app: hello
        realease: stable
        tier: helloapp
        environement: production
        partition: training-k8s
    spec:
      containers:
      - name: hello
        image: kelseyhightower/hello:2.0.0
        ports:
          - name: hello-port
            containerPort: 80
        resources:
          limits:
            cpu: 0.3
            memory: 50Mi
