apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellov1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      realease: stable
      tier: helloapp
      environement: production
      partition: training-k8s
      version: 1.0.0  
  template:
    metadata:
      labels:
        app: hello
        realease: stable
        tier: helloapp
        environement: production
        partition: training-k8s
        version: 1.0.0  
    spec:
      containers:
      - name: hello
        image: kelseyhightower/hello:1.0.0
        ports:
          - name: hello-port
            containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: 50Mi
