apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: auth-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
      realease: stable
      tier: authentification
      environement: dev
      partition: training-k8s
  template:
    metadata:
      labels:
        app: auth
        realease: stable
        tier: authentification
        environement: dev
        partition: training-k8s
    spec:
      containers:
      - name: auth
        image: "kelseyhightower/auth:1.0.0"
        ports:
        - name: http
          containerPort: 80
        - name: health
          containerPort: 81
