apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      release: stable
      tier: helloapp
      environement: production
      partition: training-k8s
  template:
    metadata:
      labels:
        app: hello
        release: stable
        tier: helloapp
        environement: production
        partition: training-k8s 
    spec:
      containers:
      - name: hello
        image: kelseyhightower/hello:1.0.0
        ports:
          - name: hello-port
            containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
