apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
      track: stable_1.0.0
  template:
    metadata:
      labels:
        track: stable_1.0.0
        app: auth
    spec:
      containers:
      - name: auth
        image: kelseyhightower/auth:1.0.0
        ports:
          - name: auth-port
            containerPort: 80
        resources:
          limits:
            cpu: 200m # 0.2 works too
            memory: 20Mi
