apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
      app: auth
      environement: production
      partition: training-k8s
      release: stable
      tier: authentification
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
    - protocol: "TCP"
      port: 81
      targetPort: 81
