apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
    realease: stable
    tier: helloapp
    environement: production
    partition: training-k8s
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
    - protocol: "TCP"
      port: 81
      targetPort: 81
