apiVersion: v1
kind: Pod
metadata:
  name: auth
  labels:
    app: auth
    realease: stable
    tier: authentification
    environement: dev
    partition: training-k8s
spec:
  containers:
    - name: auth
      image: "kelseyhightower/auth:1.0.0"
      ports:
      - name: http
        containerPort: 80
      - name: health
        containerPort: 81
      resources:
        limits:
          cpu: 200m # 0.2 works too
          memory: 20Mi

