apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
    realease: stable
    tier: fronthttps
    environement: dev
    partition: training-k8s
spec:
  containers:
  - name: nginx
    image: nginx:1.9.14
    ports:
    - containerPort: 80
