apiVersion: v1
kind: Pod
metadata:
  name: auth
  labels:
    app: auth
    track: stable_1.0.0
spec:
  containers:
    - name: auth
      image: kelseyhightower/auth:1.0.0
      ports:
        - name: http
          containerPort: 8080
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"