apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    track: stable_1.0.0
    app: hello
spec:
  containers:
    - name: hello
      image: kelseyhightower/hello:1.0.0
      ports:
        - name: auth-port
          containerPort: 8080
      resources:
        limits:
          cpu: 300m
          memory: 50Mi
