apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
    realease: stable
    tier: webserver
    environement: dev
    partition: training-k8s
spec:
  containers:
    - name: hello
      image: kelseyhightower/hello:1.0.0
      ports:
        - name: http
          containerPort: 80
      resources:
        limits:
          cpu: 0.3
          memory: "50Mi"



