
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector: // Une des manières possibles. Exemple avec matchLabels et matchExpressions
    matchLabels:
      app: auth
      environement: production
      release: stable
      version: 1.0.0 
    matchExpressions:  
      - {key: partition, operator: In, values: [training-k8s, training-treeptik-k8s, super-students]}
      - {key: tier, operator: NotIn, values: [frontssl, webserver]} 
  template:
    metadata:
      labels:
        app: auth
        environement: production
        partition: training-k8s
        release: stable
        tier: authentification
        version: 1.0.0   
    spec:
      containers:
        - name: auth
          image: "kelseyhightower/auth:1.0.0"
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 81
          resources:
            limits:
              cpu: 0.2
              memory: "10Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 81
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 81
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1